### ISSUE TITLE
Docker run for influx and grafana already running

### ISSUE THREAD

**Issue by corasaniti** [xinmans/docker-tailscale-monitor#2]
Very interesting project, congratulations. But how can I do if I already have an installation of influx and grafana?
Can you provide me with the dockler run for existing Inlfux and Grafana installations?
Thanks
PC

**Comment by corasaniti** [comment]
Also I tried searching for your image on DockerHub and ghcr but couldn't find it tailscale-monitor:latest
There are no instructions on how to build the container... :-(
Thanks again
PC

**Comment by Eliam077** [comment]
corasaniti,

there is instruction to build the contenair,
there is a dockerfile in tailscale folder (if you git clone the repository)

**Comment by corasaniti** [comment]
@Eliam077 
So assuming you build and tag the image with the following command

`docker build -f Dockerfile --tag corpie/tailscale-monitor .`

I should be able to run the container with the following docker run

`docker run -d --name=tailscale-monitor --hostname=tailscale-monitor -e TAILSCALE_INTERVAL=3600 -e TAILSCALE_HOST=192.168.2.190 -e INFLUXDB_HOST=192.168.2.190 -e INFLUXDB_DB=tailscale -e TAILSCALE_SKEY=xxxxxx -e TAILSCALE_USER=xxxxx --restart=always corpi/tailscale-monitor:latest	  `

right?
Thanks

**Comment by corasaniti** [comment]
@Eliam077 
i was not able to start container after successful build here is the error log

[INFO][2023-05-14 10:10:44] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:44] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:45] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:46] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:47] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:49] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:53] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:59] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:11:13] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:11:39] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:12:30] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')

**Comment by Eliam077** [comment]
I am in the same point.

Look my issue
________________________________
De : Piero Corasaniti ***@***.***>
Envoyé : Sunday, May 14, 2023 12:13:20 PM
À : xinmans/docker-tailscale-monitor ***@***.***>
Cc : Eliam077 ***@***.***>; Mention ***@***.***>
Objet : Re: [xinmans/docker-tailscale-monitor] Docker run for influx and grafana already running (Issue #2)


@Eliam077<https://github.com/Eliam077>
i was not able to start container after successful build here is the error log

[INFO][2023-05-14 10:10:44] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:44] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:45] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:46] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:47] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:49] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:53] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:10:59] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:11:13] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:11:39] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')
[INFO][2023-05-14 10:12:30] Starting get tailscale derper status from api.tailscale.com ...
Cannot read properties of undefined (reading 'forEach')

**Comment by corasaniti** [comment]
@Eliam077 
Ok I used the AUTHKey instead APIKey. Everything works fine...
This is my docker run after build and tagging corpie/tailscale-monitor images from Tailscale dir Dockerfile....

docker run -d \
        --name=tailscale-monitor \
        --hostname=tailscale-monitor \
        -e TAILSCALE_INTERVAL=3600 \
        -e TAILSCALE_HOST=192.168.2.190 \
        -e INFLUXDB_HOST=192.168.2.190 \
        -e INFLUXDB_DB=tailscale \
        -e TAILSCALE_SKEY=xxxxxxxx \
        -e TAILSCALE_USER=yyyyyyy \
        --restart=always \
        corpie/tailscale-monitor:latest

Thanks for the suggestion
:-)

**Comment by corasaniti** [comment]
@Eliam077 
Thanks again. I closed this issue/request
